# Generated by Django 4.2 on 2023-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_being_prepared', models.BooleanField(default=False)),
            ],
        ),
    ]
