# Generated by Django 4.2 on 2023-05-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineQueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_being_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
