# Generated by Django 4.2 on 2023-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(error_messages={'detail': 'You dont select card for payment !'}, help_text={'unique': 'Select card for your payment '}, max_length=50)),
                ('card_number', models.IntegerField(error_messages={'detail': 'Please enter the correct card number'}, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pay_amount', models.IntegerField()),
                ('balance', models.IntegerField(null=True)),
            ],
        ),
    ]
