# Generated by Django 4.2 on 2023-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePay', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymethod',
            name='card_number',
            field=models.CharField(error_messages={'detail': 'Please enter the correct card number'}, unique=True),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='card_type',
            field=models.CharField(choices=[('Uzcard', 'uzcard'), ('Humo', 'humo'), ('Visa', 'visa'), ('Unionpay', 'unionpay'), ('Mastercard', 'mastercard')], error_messages={'detail': 'You dont select card for payment !'}, help_text='Select card for your payment ', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='pay_amount',
            field=models.CharField(),
        ),
    ]
