# Generated by Django 4.2 on 2023-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePay', '0003_alter_paymethod_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymethod',
            name='pay_amount',
            field=models.BigIntegerField(),
        ),
    ]
