# Generated by Django 4.2 on 2023-06-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePay', '0004_alter_paymethod_pay_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymethod',
            name='balance',
            field=models.BigIntegerField(null=True),
        ),
    ]
