# Generated by Django 4.2 on 2023-06-02 09:28

import OnlinePay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePay', '0005_alter_paymethod_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymethod',
            name='card_number',
            field=models.CharField(error_messages={'detail': 'Please enter the correct card number'}, unique=True, validators=[OnlinePay.models.validate_card_number]),
        ),
    ]
