# Generated by Django 4.2 on 2023-05-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='price',
            new_name='food_price',
        ),
    ]
