# Generated by Django 4.2 on 2023-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
