# Generated by Django 4.2 on 2023-06-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0002_initial'),
        ('onlineQueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order_queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_order', to='onlineQueue.queue'),
        ),
        migrations.AddField(
            model_name='basket',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_food', to='basket.basket'),
        ),
    ]
